___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,3)

array([0, 3, 6, 9])

### zeros and ones

Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
print(np.zeros((5,5)))

# we can pass tuple (a,b) as a argument to represent row and column of np array
a = (2,5)
print(np.zeros(a))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [25]:
# syntax(start,end,number of element)
# we can generate an array from start to end with specific number of element
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
# start from zero, end at ten with 50 elements
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [33]:
# rand function will return real number from 0 (inclusive) to 1 (exclusive) [0,1)
# syntax np.random.rand(n) -> will return array, n is number of elements
# result is uniform distribution
np.random.rand(3)

array([0.33010734, 0.93018168, 0.81074741])

In [37]:
print(np.random.rand(5,5))
print()
print(np.random.rand(2,3))

[[0.26416721 0.10157529 0.84900078 0.12944836 0.03803137]
 [0.35515451 0.40867323 0.93648464 0.63176638 0.57566751]
 [0.22498791 0.84801048 0.40574122 0.01861561 0.70813664]
 [0.36354579 0.92157411 0.14420802 0.71639993 0.78676613]
 [0.79725801 0.90515241 0.74629667 0.95666257 0.01459249]]

[[0.05186783 0.43461597 0.68253477]
 [0.83310546 0.44890756 0.22141677]]


### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [40]:
np.random.randn(2)

array([0.64770828, 1.44087553])

In [39]:
np.random.randn(5,5)

array([[-1.57067866,  0.79814279, -0.60061798, -0.50969959,  0.08732973],
       [-0.12331169, -0.46335077, -0.79182503,  0.67030491, -0.43818543],
       [-0.84128664, -1.14197976, -1.25869852, -0.00223956, -0.19187876],
       [ 0.34728776, -0.6101644 ,  0.55176912,  0.19250138,  0.60487849],
       [ 0.14603758, -1.62702512, -0.39377124, -1.3204505 ,  1.60408528]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [42]:
# syntax np.random.randint(low,high,n) -> n is optional
np.random.randint(1,100)

71

In [43]:
np.random.randint(1,100,10)

array([59, 97,  4, 50, 77, 34, 55, 33, 47, 73])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [49]:
arr = np.arange(24)
ranarr = np.random.randint(0,50,10)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
ranarr

array([43, 46, 32, 17,  5, 42,  7,  9,  7, 49])

## Reshape
Returns an array containing the same data with a new shape.

In [51]:
# if we have an np array, we can call the useful methods
# reshape the array to be n rown and m columns -> total size must be the same
# we can call method directly from array of np
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [53]:
# argmax(), argminn() -> is a function to find index if max, min
ranarr

array([43, 46, 32, 17,  5, 42,  7,  9,  7, 49])

In [56]:
ranarr.max()

49

In [57]:
ranarr.argmax()

9

In [58]:
ranarr.min()

5

In [59]:
ranarr.argmin()

4

## Shape

Shape is an attribute that arrays have (not a method):

In [67]:
# Vector
print(arr.shape)
print(arr[1])

(24,)
1


In [65]:
# Notice the two sets of brackets
# reshape arr to be matrix of 1 row and 24 columns
arr.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [68]:
arr.reshape(1,24).shape

(1, 24)

In [69]:
arr.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [71]:
arr.reshape(24,1).shape

(24, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
# default int of python is int 64 bits
arr.dtype

dtype('int64')

In [81]:
from numpy.random import randint

In [86]:
randint(0,10,3)

array([6, 8, 7])

# Great Job!